- hosts: localhost
  become: true
  tasks:
    - name: Update repositories cache
      apt:
        update_cache: true
    - name: Configure keyboard layouts
      lineinfile:
        path: /etc/default/keyboard
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - regexp: "^XKBLAYOUT="
          line: 'XKBLAYOUT="de,us"'
        - regexp: "^XKBVARIANT="
          line: 'XKBVARIANT="neo,"'
      notify: Reconfigure keyboard configuration
    - name: Set up desktop environment
      block:
        - name: Install packages
          apt:
            name:
              - virtualbox-guest-dkms
              - virtualbox-guest-utils
              - virtualbox-guest-x11
              - xfce4
        - name: Allow anyone to use it
          lineinfile:
            path: /etc/X11/Xwrapper.config
            regexp: "^allowed_users="
            line: allowed_users=anybody
    - name: Install packages
      apt:
        name:
          - firefox
    - name: Update all present packages
      apt:
        upgrade: full
  handlers:
    - name: Reconfigure keyboard configuration
      command: dpkg-reconfigure --frontend noninteractive keyboard-configuration
