- hosts: localhost
  tasks:
    - name: Update repositories cache
      become: true
      apt:
        update_cache: true
    - name: Configure keyboard layouts
      become: true
      lineinfile:
        path: /etc/default/keyboard
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - regexp: "^XKBLAYOUT="
          line: 'XKBLAYOUT="de,us"'
        - regexp: "^XKBVARIANT="
          line: 'XKBVARIANT="neo,"'
      notify: Reconfigure keyboard configuration
    - name: Set up desktop environment
      block:
        - name: Install packages
          become: true
          apt:
            name:
              - virtualbox-guest-dkms
              - virtualbox-guest-utils
              - virtualbox-guest-x11
              - xfce4
        - name: Allow anyone to use it
          become: true
          lineinfile:
            path: /etc/X11/Xwrapper.config
            regexp: "^allowed_users="
            line: allowed_users=anybody
        - name: Start it at login
          lineinfile:
            path: "{{ ansible_env.HOME }}/.profile"
            regexp: " exec startx "
            line: 'if [[ "${XDG_VTNR}" -eq 1 ]]; then exec startx ; fi'
    - name: Install packages
      become: true
      apt:
        name:
          - firefox
    - name: Modify Firefox default preferences
      become: true
      lineinfile:
        path: /etc/firefox/syspref.js
        line: "{{ item }}"
      with_items:
        - 'pref("browser.startup.homepage", "{{ home_page }}");'
        - 'pref("places.history.enabled", false);'
        - 'pref("signon.rememberSignons", false);'
    - name: Update all present packages
      become: true
      apt:
        upgrade: full
  handlers:
    - name: Reconfigure keyboard configuration
      become: true
      command: dpkg-reconfigure --frontend noninteractive keyboard-configuration
