- name: Do system-wide setup
  hosts: localhost
  tasks:
    - name: Update repositories cache
      become: true
      ansible.builtin.apt:
        update_cache: true

    - name: Install packages
      become: true
      ansible.builtin.package:
        name:
          - firefox
          - virtualbox-guest-dkms
          - virtualbox-guest-utils
          - virtualbox-guest-x11
          - xfce4

    - name: Configure keyboard layouts
      become: true
      ansible.builtin.lineinfile:
        line: "{{ item.line }}"
        path: /etc/default/keyboard
        regexp: "{{ item.regexp }}"
      with_items:
        - line: 'XKBLAYOUT="de,us"'
          regexp: "^XKBLAYOUT="
        - line: 'XKBVARIANT="neo,"'
          regexp: "^XKBVARIANT="

    - name: Configure Firefox
      become: true
      ansible.builtin.copy:
        dest: /etc/firefox
        mode: preserve
        src: firefox/policies

    - name: Use Xfce by default
      become: true
      community.general.ini_file:
        mode: u=rw,g=,o=
        option: XSession
        path: /var/lib/AccountsService/users/vagrant
        section: User
        value: xfce

    - name: Update all present packages
      become: true
      ansible.builtin.apt:
        upgrade: full
